"""empty message

Revision ID: 063bd2880d70
Revises: 8e2399013795
Create Date: 2025-06-16 17:06:07.956401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063bd2880d70'
down_revision = '8e2399013795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forwarded_message_reference', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['forwarded_message_reference'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('forwarded_message_reference')

    # ### end Alembic commands ###
