"""empty message

Revision ID: 0a3e44cccc9e
Revises: 630604184ddf
Create Date: 2025-06-09 01:37:45.872520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3e44cccc9e'
down_revision = '630604184ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=24), nullable=False))
        batch_op.add_column(sa.Column('path', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['path'])
        batch_op.drop_constraint(batch_op.f('posts_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('posts_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('path')
        batch_op.drop_column('title')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
