"""empty message

Revision ID: 0a64999b9c1c
Revises: 8528f3c0753a
Create Date: 2025-07-28 18:08:27.877861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a64999b9c1c'
down_revision = '8528f3c0753a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_reports', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('close_reports', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_permissions', schema=None) as batch_op:
        batch_op.drop_column('close_reports')
        batch_op.drop_column('list_reports')

    # ### end Alembic commands ###
