"""empty message

Revision ID: 106c7a2cf3b9
Revises: 5b805fcba831
Create Date: 2025-06-29 18:38:48.825956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106c7a2cf3b9'
down_revision = '5b805fcba831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_verifications', schema=None) as batch_op:
        batch_op.drop_column('callback_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('callback_url', sa.VARCHAR(), server_default=sa.text("'profile.profile'::character varying"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
