"""empty message

Revision ID: 1c7003672877
Revises: 8a7ec95b5f97
Create Date: 2025-06-29 22:32:08.204806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7003672877'
down_revision = '8a7ec95b5f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_users', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edit_users', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('list_comments', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_permissions', schema=None) as batch_op:
        batch_op.drop_column('list_comments')
        batch_op.drop_column('edit_users')
        batch_op.drop_column('list_users')

    # ### end Alembic commands ###
