"""empty message

Revision ID: 22fb27a2dfbc
Revises: c75962eb8fd7
Create Date: 2025-06-25 00:37:36.263277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22fb27a2dfbc'
down_revision = 'c75962eb8fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reposted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reposted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_forwarded')
        batch_op.drop_column('forwarded_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forwarded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_forwarded', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('reposted_at')
        batch_op.drop_column('is_reposted')

    # ### end Alembic commands ###
