"""empty message

Revision ID: 570ba3650dce
Revises: dbb4fcfa400b
Create Date: 2025-06-09 16:20:53.692141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570ba3650dce'
down_revision = 'dbb4fcfa400b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=4096),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
