"""empty message

Revision ID: 630604184ddf
Revises: d361c214d6fd
Create Date: 2025-06-03 06:11:40.426507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630604184ddf'
down_revision = 'd361c214d6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_column('is_accepted')

    # ### end Alembic commands ###
