"""empty message

Revision ID: 8528f3c0753a
Revises: f3eee7bd4bf2
Create Date: 2025-07-25 14:32:26.748837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8528f3c0753a'
down_revision = 'f3eee7bd4bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('tags_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey'))
    )
    # ### end Alembic commands ###
