"""empty message

Revision ID: 880e7c33de10
Revises: adcfa16d50b0
Create Date: 2025-06-12 16:31:53.077276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880e7c33de10'
down_revision = 'adcfa16d50b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
