"""empty message

Revision ID: 888c504c2b13
Revises: ee0625a815a9
Create Date: 2025-06-12 22:18:21.635560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888c504c2b13'
down_revision = 'ee0625a815a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_verifications', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('picture')

    with op.batch_alter_table('user_verifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
