"""empty message

Revision ID: 8e2399013795
Revises: 5e04df7ff878
Create Date: 2025-06-16 16:57:27.900394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2399013795'
down_revision = '5e04df7ff878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_forwarded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('forwarded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('edited_at')
        batch_op.drop_column('is_edited')
        batch_op.drop_column('forwarded_at')
        batch_op.drop_column('is_forwarded')

    # ### end Alembic commands ###
