"""empty message

Revision ID: 918ef1328fed
Revises: 0a64999b9c1c
Create Date: 2025-07-28 19:42:54.975823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918ef1328fed'
down_revision = '0a64999b9c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reports_author_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('reports_author_id_fkey'), 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###
