"""empty message

Revision ID: bed6d5577ddc
Revises: 0a3e44cccc9e
Create Date: 2025-06-09 02:11:09.706217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed6d5577ddc'
down_revision = '0a3e44cccc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('web_path', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('posts_path_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['web_path'])
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('posts_path_key'), ['path'])
        batch_op.drop_column('web_path')

    # ### end Alembic commands ###
