"""empty message

Revision ID: c75962eb8fd7
Revises: 651a2b2e56d6
Create Date: 2025-06-25 00:33:45.423674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75962eb8fd7'
down_revision = '651a2b2e56d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_forwarded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('forwarded_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'posts', ['reference'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('forwarded_at')
        batch_op.drop_column('reference')
        batch_op.drop_column('is_forwarded')

    # ### end Alembic commands ###
