"""empty message

Revision ID: d2224ec31ff4
Revises: 382cb0c0ac9f
Create Date: 2025-07-03 19:12:58.544415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2224ec31ff4'
down_revision = '382cb0c0ac9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_permissions', schema=None) as batch_op:
        batch_op.drop_column('add_admins')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_admins', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
