"""empty message

Revision ID: dbb4fcfa400b
Revises: fb6c4bb5394c
Create Date: 2025-06-09 16:18:45.754978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb4fcfa400b'
down_revision = 'fb6c4bb5394c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('posts_web_path_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.drop_column('web_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('web_path', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('posts_web_path_key'), ['web_path'])
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
