"""empty message

Revision ID: e74246829282
Revises: 063bd2880d70
Create Date: 2025-06-16 17:10:01.557118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74246829282'
down_revision = '063bd2880d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('messages_forwarded_message_reference_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'messages', ['forwarded_message_reference'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_forwarded_message_reference_fkey'), 'users', ['forwarded_message_reference'], ['id'])

    # ### end Alembic commands ###
