"""empty message

Revision ID: f0a11ed1bddb
Revises: e74246829282
Create Date: 2025-06-16 17:49:57.853262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a11ed1bddb'
down_revision = 'e74246829282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('messages_forwarded_message_reference_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'messages', ['reference'], ['id'])
        batch_op.drop_column('forwarded_message_reference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forwarded_message_reference', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_forwarded_message_reference_fkey'), 'messages', ['forwarded_message_reference'], ['id'])
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
