"""empty message

Revision ID: f3eee7bd4bf2
Revises: eedc7ba7f148
Create Date: 2025-07-13 18:29:43.829505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3eee7bd4bf2'
down_revision = 'eedc7ba7f148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_table', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reference_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('reference_id')
        batch_op.drop_column('reference_table')

    # ### end Alembic commands ###
