"""empty message

Revision ID: fb6c4bb5394c
Revises: bed6d5577ddc
Create Date: 2025-06-09 02:47:09.583547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6c4bb5394c'
down_revision = 'bed6d5577ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)

    # ### end Alembic commands ###
