"""empty message

Revision ID: ffa86caeeba0
Revises: db0ae0fdc533
Create Date: 2025-06-23 20:58:35.395876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffa86caeeba0'
down_revision = 'db0ae0fdc533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('posts_reference_fkey'), type_='foreignkey')
        batch_op.drop_column('reference')
        batch_op.drop_column('forwarded_at')
        batch_op.drop_column('is_forwarded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_forwarded', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('forwarded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reference', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('posts_reference_fkey'), 'messages', ['reference'], ['id'])

    # ### end Alembic commands ###
